In [1]:
import numpy as np

The core of the numpy library is n-dimensional arrays

In [2]:
lst = [
    [1, 2, 3],
    [3, 4, 5]
]
two_d_arr = np.array(lst)
two_d_arr

array([[1, 2, 3],
       [3, 4, 5]])

Data types are automatically inferred and can be changed. But ndarrays but have a homegenous data type so that data can be stored contiguously in memory.

In [3]:
# Automatically infers data type
# Can only have 1 data type
print(f'Data type of original array: {two_d_arr.dtype}')
# We can convert the data type as required
float_32_arr = two_d_arr.astype(np.float32)
print(f'Data type of float_32_arr: {float_32_arr.dtype}')

Data type of original array: int64
Data type of float_32_arr: float32


Dimensions and shape can be used to find the size of the matrix

In [4]:
# Check the dimensions of the n dimensional array
print(f'Dimensions of array (ndim):{two_d_arr.ndim}')
print(f'Shape of the array: {two_d_arr.shape}')

Dimensions of array (ndim):2
Shape of the array: (2, 3)


We can get specific info about a function using ?

In [5]:
# Get specific info regarding a function
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensur

There are various functions to fill arrays when needed for computations

In [6]:
# Initialize an array of all ones
ones = np.ones((2, 3), np.int32)
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [7]:
# Initialize an array of all zeros
zeros = np.zeros((4, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# Initialize an identity matrix
identity = np.eye(3, 3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Initialize a diagonal given an array
diag = np.diag([1, 4 , 54, 7])
diag

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 54,  0],
       [ 0,  0,  0,  7]])

In [10]:
# Initialize an array given an interval length and the end and start of the interval
# Can work on float values unlike pythons list function
arange = np.arange(1.0, 3.1, 0.14)
arange

array([1.  , 1.14, 1.28, 1.42, 1.56, 1.7 , 1.84, 1.98, 2.12, 2.26, 2.4 ,
       2.54, 2.68, 2.82, 2.96])

In [11]:
# Given the interval start, end and number of intevals required
# Automatically splits the interval
linspace = np.linspace(1.0, 3.0, 20)
linspace

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

Indexing a 2 dimensional array is somewhat similar to python lists

In [12]:
print(f'For array: {two_d_arr}')
# Print the element on the right corner
print(f'Idx: -1, -1: {two_d_arr[0, -2]}')
# Print the first row
print(f'Idx of [0]: {two_d_arr[0]}')
# Print the last row
print(f'Idx of [-1]: {two_d_arr[-1]}')
# Slicing parts
print(f'Sliced idx of [0] from[1:3] {two_d_arr[0][1:3]}')


For array: [[1 2 3]
 [3 4 5]]
Idx: -1, -1: 2
Idx of [0]: [1 2 3]
Idx of [-1]: [3 4 5]
Sliced idx of [0] from[1:3] [2 3]
