Adding 1 to every element in a matrix in python is tedious and inefficient

In [36]:
lst = [
    [1, 2, 3],
	[4, 5, 6]
]

for row_idx, row_val in enumerate(lst):
	for col_idx, col_val in enumerate(row_val):
		lst[row_idx][col_idx] += 1

print(lst)

[[2, 3, 4], [5, 6, 7]]


We can use a unfunc here implemented in C instead

In [37]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.add(arr, 1)
arr

array([[2, 3, 4],
       [5, 6, 7]])

Numpy uses operator overloading for arithmetic operations. Therefore we can call the functions directly using arithmetic operators. Numpy uses broadcasting when performing matrix operations for which the dimensions don't match.

In [38]:
arr = arr + 2
print(arr)
arr = arr ** 2
print(arr)

[[4 5 6]
 [7 8 9]]
[[16 25 36]
 [49 64 81]]


Reduce helps to reduce the dimensions of the ndarray by combining values along an axis using a mathematical operator. Uses axis 0 by default if not specified.

In [39]:
arr2 = np.add.reduce(arr)
print(arr2)
arr3 = np.add.reduce(arr, axis=1)
print(arr3)
arr4 = arr.sum(axis = 0)
print(arr4)

[ 65  89 117]
[ 77 194]
[ 65  89 117]


To get sample std deviation and variance we have to use degrees of freedom if we want to include bessel's correction for sample std deviation		

In [40]:
print(np.std(arr))
print(np.std(arr, ddof=1))

22.34141644768498
24.473795510028


Arg sort returns the original indexes of the sorted array

In [41]:
arr = np.array([5, 6, 1, 3])
print(np.sort(arr))
print(np.argsort(arr))

[1 3 5 6]
[2 3 0 1]


Get max and index of max

In [42]:
max = np.max(arr)
idx = np.argmax(arr)

print(f'Max element:  {max} found at index: {idx}')

Max element:  6 found at index: 1
