Slicing and indexing creates a shallow copy of the original in numpy

In [11]:
import  numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
first_row = arr[0]
print(f'First row of array using indexing: \n{first_row}')
sliced_val = arr[:, 1:2]
print(f'Sliced columns from idx 1 to 2: \n{sliced_val}')
# Will alter the original matrix
first_row += 1
print(f'Changing the indexed copy also affect the array: \n{arr}')
sliced_val +=  5
print(f'Changing the sliced copy also affects the array: \n{arr}')

First row of array using indexing: 
[1 2 3]
Sliced columns from idx 1 to 2: 
[[2]
 [5]]
Changing the indexed copy also affect the array: 
[[2 3 4]
 [4 5 6]]
Changing the sliced copy also affects the array: 
[[ 2  8  4]
 [ 4 10  6]]


If we want to make a deep copy of a part of an array we can use the copy method	

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
first_row = arr[0].copy()
print(f'First row of array using indexing: \n{first_row}')
sliced_val = arr[:, 1:2].copy()
print(f'Sliced columns from idx 1 to 2: \n{sliced_val}')
# Will alter the original matrix
first_row += 1
print(f'Changing the deep indexed copy no longer affects the array: \n{arr}')
sliced_val +=  5
print(f'Changing the deep sliced copy no longer affects the array: \n{arr}')

First row of array using indexing: 
[1 2 3]
Sliced columns from idx 1 to 2: 
[[2]
 [5]]
Changing the deep indexed copy no longer affects the array: 
[[1 2 3]
 [4 5 6]]
Changing the deep sliced copy no longer affects the array: 
[[1 2 3]
 [4 5 6]]


Fancy indexing is also an option that lets us make deep copies. We can also rearrange the array and take specific indexes from the input array using this approach.	

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
fancy_indexed_copy = arr[:, [0, 2]]
print(f"Fancy indexed copt of first and second column: \n {fancy_indexed_copy}")
fancy_indexed_copy2 = arr[:, [2, 0]]
print(f"Fancy indexed copy of third and first column in opposite order: \n {fancy_indexed_copy2}")
fancy_indexed_copy += 1
print(f'Adding one to the fancy indexed copy: \n{fancy_indexed_copy}')
print(f'Original array is unchanged: \n{arr}')

Fancy indexed copt of first and second column: 
 [[1 3]
 [4 6]]
Fancy indexed copy of third and first column in opposite order: 
 [[3 1]
 [6 4]]
Adding one to the fancy indexed copy: 
[[2 4]
 [5 7]]
Original array is unchanged: 
[[1 2 3]
 [4 5 6]]
