We can use boolean masks to add conditions to our numpy array	

In [6]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
greater_3_maks = arr > 3
print(greater_3_maks)

[[False False False]
 [ True  True  True]]


We can then get the elements that the mask corresponds to by using it with the og array	

In [7]:
print(arr[greater_3_maks])

[4 5 6]


We can chain together different condition using logical operators

In [8]:
combined_mask = (arr > 3) & (arr < 6)
print(combined_mask)
print(arr[combined_mask])

[[False False False]
 [ True  True False]]
[4 5]


We can use masks to change the values in our array based on conditions

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.where(arr> 3, 1, 0))


[[0 0 0]
 [1 1 1]]
