Numpy has different random number generators. It will create a random array.

In [16]:
import numpy as np 

print(np.random.rand(3))


[0.9807642  0.68482974 0.4809319 ]


We can pass a seed so the generations are same.

In [17]:
np.random.seed(123)

print(np.random.rand(3))
print(np.random.rand(3))

[0.69646919 0.28613933 0.22685145]
[0.55131477 0.71946897 0.42310646]


Setting seed affects all calls. A more flexible option is to use the default rng class or random state object. This provides more flexibility with your code and we can choose which seed to apply.

In [18]:
rng1 = np.random.default_rng(seed=123)
val1 = rng1.random(3)
val2 = rng1.random(3)
print(f'Random number generator seed 123: \n{val1}')
print(f'Random number generator sequential call seed 123: \n {val2}')


rng2 = np.random.default_rng(seed=144)
val1 = rng2.random(3)
val2 = rng2.random(3)
print(f'Random number generator seed 144: \n{val1}')
print(f'Random number generator sequential call seed 144: \n {val2}')

Random number generator seed 123: 
[0.68235186 0.05382102 0.22035987]
Random number generator sequential call seed 123: 
 [0.18437181 0.1759059  0.81209451]
Random number generator seed 144: 
[0.79276184 0.05968737 0.29967511]
Random number generator sequential call seed 144: 
 [0.09212141 0.295691   0.07230802]
