Reshaping is important when we want to modify dimensions of an array. Useful when we need a specific format for a function.

In [7]:
import numpy as np 
arr = np.array([1, 2, 3, 3, 4, 5])
arr_2d = arr.reshape(2, 3)
print(arr_2d)

[[1 2 3]
 [3 4 5]]


Reshape returns a shallow copy or memory view

In [8]:
np.may_share_memory(arr, arr_2d)

True

We  can use flatten if we want to create a deep copy	

In [9]:
flat_arr = arr.flatten() 
np.may_share_memory(flat_arr, arr)

False

The concat function lets us combine arrays along an axis. If not specified defaults to axis 0

In [10]:
concat_arr = np.concatenate((arr, arr), axis=0)
print(concat_arr)
print(concat_arr.shape)

[1 2 3 3 4 5 1 2 3 3 4 5]
(12,)


In [11]:
arr = np.array([[1, 2 , 3], [3, 4, 5]])
concat_arr = np.concatenate((arr, arr), axis=1)
print(concat_arr)
print(concat_arr.shape)

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
(2, 6)
