For dot product calculations the dimensions have to match. However, numpy can be forgiving as it uses broadcasting

In [9]:
import numpy as np 

row_vector = np.array([1, 2, 3])
row_vector

array([1, 2, 3])

In [10]:
column_vector = np.array([1, 2, 3]).reshape(-1, 1)
column_vector

array([[1],
       [2],
       [3]])

In [11]:
print(np.dot(row_vector, column_vector))

[14]


We can also transpose an array

In [12]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(matrix.transpose())


[[1 4]
 [2 5]
 [3 6]]
